product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }
Accueil:
    path:     /Accueil
    defaults: { _controller: ProductBundle:Store:index }
Contact:
    path:     /Contact
    defaults: { _controller: ProductBundle:Store:contact }
